### ISSUE TITLE
FreeBSD.  Start with error "Can't init serviceNo service system detected."

### ISSUE THREAD

**Issue by mavalery** [rekby/lets-proxy#25]
FreeBSDx64 vervion 10.3, clean install.
root#  ./lets-proxy
ERRO[2017-02-11T01:37:14+02:00] Can't init serviceNo service system detected.

**Comment by rekby** [comment]
lets-proxy doesn't support service (auto install daemon) actions for freebsd now.
I have fixed the message text and level (from error to info).
The fix will contained in next release. Now you can ignore the message and use the program.

Fixed by 9efc0926c495016f31c1afa1c30da1d18e767d69
