### ISSUE TITLE
Shell install scripts

### ISSUE THREAD

**Issue by olliephillips** [rekby/lets-proxy#33]
Hello. 

Appreciate this is trivial to do, but shell scripts to get lets-proxy onto the server might be useful to many? 

I have [this bash script](https://github.com/olliephillips/lets-proxy-quick). It sets up lets-proxy in a separate directory, with all paths resolving, in whitelist mode, and with escalated privileges as well as daemonized. 

It currently pulls a recent binary from your repo. Maybe it can follow a redirect to pull `/latest`. I haven't looked at that.

The script offers a consistent deployment of lets-proxy, so it only acts when allowed to by adding domains to the whitelist. Feels like has a smaller footprint on the server since put in a folder, and no configuration to consider. Maybe others could use similar?

I'm sure you could improve it, I just wanted to float the idea and feedback that it has been useful to me.

Certbot client feels a bit like a sledgehammer, and I worry about letting it loose on production servers, lets-proxy feels much better, much slicker, and with the whitelist, HTTPS rollout is still totally under control. 

An easy deploy of lets-proxy maybe could get more people using it?

**Comment by rekby** [comment]
Hello.

The script ok for local usage, but bad for public:
1. It work in relative path - install destination depends from folder, that scripts was run.
2. You use setcap, but don't create restrictes user - lets-proxy run as root. You may remove setcap or have to create additional user. Setcap no need for root.
3. It doesn't allow select between i386, adm64 arch.
may be some else.

I think about install script, but I think it should be usual package: rpm, deb, overlay, etc.
I think about install-script it temporary workaround, similar to --install key. I think one bad workaround better, then two bad workaround. Becouse it need to support, fix bugs, etc.
I think next step must be normal packages for package systems for OSes (.msi for windows, .deb for ubuntu/debian, rpm for redhat/centos/oracle/..., overlay for gentoo, etc.).

You can get latest release url from bash:
curl https://api.github.com/repos/rekby/lets-proxy/releases/latest | grep download_url | cut -d '"' -f 4 | grep linux-amd64
