### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by rekby** [rekby/lets-proxy#35]

**Comment by s0t** [comment]
ssllabs.com/ssltest

Protocol Support options:
-min-tls tls10 # Protocol Support 90%
-min-tls tls11 # Protocol Support 95%
-min-tls tls12 # Protocol Support 100%

Key Exchange options:
-private-key-len 2048 # (default) + 384 EC 90%
-private-key-len 4096 # + 384 EC 100%

**Comment by olliephillips** [comment]
Do you have a tree/outline of the Wiki sections you're thinking of. Maybe I can spare some time to assist.

**Comment by rekby** [comment]
Hello.
No, I have no ideas for wiki sections now.

May be pages with more detailed description of parameters, then in --help.
I have no expirence in documentations create and don't know how to do it good.

**Comment by olliephillips** [comment]
Well, I'm happy to give it a shot. Give you as a starting point, others can build on?

**Comment by rekby** [comment]
I can create FAQ page in wiki - from few questions by email.

**Comment by olliephillips** [comment]
I see this is still open. I'd love to help if needs be. You last said you could do it based on the questions by email? If want help please say. I think the repo english description still needs to be amended - please just take the description from my fork.  

Maybe also should be listed here [Awesome Go](https://github.com/avelino/awesome-go)?

**Comment by olliephillips** [comment]
Maybe I've not been clear.  The repository description below...
![image](https://user-images.githubusercontent.com/7113347/32355535-2c0da1a4-c027-11e7-8602-ec54221398bf.png)

...would be more attractive, rewritten as the below (my fork):
![image](https://user-images.githubusercontent.com/7113347/32355585-652d5bb4-c027-11e7-9fa4-f80dcc0da8fb.png)

I'm not able to edit that or send PR for it.

**Comment by rekby** [comment]
Yes, it will better. Thanks, change repo name.

**Comment by rekby** [comment]
A send pull request to awesome

**Comment by olliephillips** [comment]
Hello @rekby. I noticed only today Let's Proxy never made it to Awesome Go. DId the PR get rejected? I would be glad to submit a pull request also? FYI this software has worked flawlessly for me for over two years now - it should be on there IMO.

**Comment by rekby** [comment]
Hello.

I didn't send PR to awesome, because lets-proxy doesn't need for go developers.
It will help for end user only - as product.

It hasn't any code for use as library, don't help to write code and etc.

**Comment by olliephillips** [comment]
That's fair, although there is a section on there for Software written in Go.  These are all standalone apps that offer no libraries AFAIK

https://github.com/avelino/awesome-go#software-packages

Your call of course. Hope you are well!

**Comment by rekby** [comment]
I think it is ok - to add lets-proxy to this list.

I will do in 1-2 month, or you can do it if you want. I will be grateful.

**Comment by rekby** [comment]
I want rewrite the app and make it more testable, simpler and better logging.

**Comment by olliephillips** [comment]
I can add for sure, but would you prefer to hold off until rewrite?

**Comment by rekby** [comment]
Ofcouse you can :)

Thanks.

**Comment by olliephillips** [comment]
Might be difficult to get this in as-is. I forked awesome-go, added and opened a PR and there are submission guidelines. 

The areas where we might struggle are godoc and providing test coverage data. There are a few exported funcs, structs and methods which are not commented. Of course, I can state it is intended to run as a CLI and it's not a package with an API. 

The other issue is proving test coverage. I imagine for the same reason you can't get the travis environment to run tests (#26) that [test coverage services like this also fail](https://gocover.io/github.com/rekby/lets-proxy)? 

Again I can explain in the PR, but there's a number of PRs held up where godoc and coverage is not provided/sufficient. What do you think?

**Comment by rekby** [comment]
Godoc can't show doc for let's proxy becouse it program (package main), godoc doesn't show any for this packages.
It hasn't public go interface.

Test was created for my own gitlab instance, becouse travis deny incoming connection and lets-encrypt can't check my domains.
For workaround - use some stubs, I want use it while rewrite code from scratch.

Test coverange show small percent - it is true. Current code has very small go tests.
I will improove testing while rewrite code.
