### ISSUE TITLE
AWS EC2

### ISSUE THREAD

**Issue by playaer** [rekby/lets-proxy#4]
Здравствуйте, в амазоне домен не проходит проверку изза того что виртуалка в приватной сети и IP получаются разные. Может можно добавить файл/флаг для апи заданного вручную, чтоб они объединялись.

Hello. In amazon EC2 domain it doesn't work becouse IP is differents. Can you add key for manual IP add.

**Comment by rekby** [comment]
Здравствуйте. 
С версии 0.6 сделано автоматическое определение внешнего IP-адреса если сервер за NAT - по-моему как раз случай amazon (если балансировщики не используются).

Попробуйте скачать последнюю версию и попробовать еще раз.

Если не получится, то вручную разрешенные адреса можно задать через ключ
--allowed-ips, подробности можно посмотреть через --help.

Если поможет только ручное задание IP через --allowed-ips - напишите пожалуйста о вашей конфигурации сети, чтобы поправить алгоритм автоопределений.

Hello
From version 0.6 it can autodetect externat IP for servers behind NAT (home,office, aws, ...). Try download latest version and try again.
If it isn't help - use key --allowed-ips, read --help for details.

If help only manual IP defined - write me please about your environment for improve autodetection.

**Comment by playaer** [comment]
Thank, update to new version fix my problems
