### ISSUE TITLE
Non updating certificates

### ISSUE THREAD

**Issue by olliephillips** [rekby/lets-proxy#42]
I'm seeing that in order for certificates to renew, the certificate files must be removed from the certificates folder and lets-proxy service stopped and started. 

I am using an older version (v0.13.3.0), but I can't see that this has been flagged as an issue in the open or closed issues. I'm running it as a service, and using the allowed-domains file configuration option.  

Just upgrade to a later version or possibly a (current) bug?

**Comment by rekby** [comment]
Hello. It is old bug, it was fixed in 0.13.3.4 https://github.com/rekby/lets-proxy/releases/tag/v0.13.3.4

It has much performance increase in 14.0.0

Just update the binary to latest version.

**Comment by olliephillips** [comment]
Hi yes, just checked the releases - found it - and came back to close. You beat me to it. Will update thanks!
