### ISSUE TITLE
Response body rewrite

### ISSUE THREAD

**Issue by olliephillips** [rekby/lets-proxy#43]
Hello, maybe this is a feature request for your radar?

It would be useful if lets-proxy could use regex to make content replacements in the proxied response body so that insecure assets urls using `http://` which could cause browser warnings could be rewritten as `//`. 

As far as I know this would pacify browsers so that the site showed as secure and we'd have less work to do on the proxied website going through all the source to manually make this type of replacement. 

Maybe this could be a flag. 

Anyway just a thought.

Have just updated to v14. It is very fast by comparison to v13. Thank you!

**Comment by rekby** [comment]
I think about it.
It has few question:
1. What do with subdomains (www and others) and upper-level domain?
2. What do with third-party links
3. What do with javascript?

**Comment by olliephillips** [comment]
In using, you'd need to know the assets are also available over https, it just negates the need to go through everything and change manually.  Links using anchor could be omitted. They won't cause a warning.

Perhaps this is edge case, but in running sites behind lets-proxy with assets that are requested over http I find myself having to spend a lot of time amending - which for older CMS generated sites can be tricky.

Cloudflare do something similar with their TLS service - flick a switch and http calls to assets in the source are swapped for https calls.

**Comment by rekby** [comment]
Ok. I think it good function and I think about to programm it.
It can take a lot of time - now I start new buisness and very busy.

I think about try that algorithm:
1. For first step parse only html code (text/html), exclude javascript.
2. Rewrite links to own domain, base domain (without www) and well-known subdomain (default - with www).
3. Extract other domains and check https connections. Rewrite links for ok-tested domains.

**Comment by rekby** [comment]
oh, I have older self-created ticket :)
https://github.com/rekby/lets-proxy/issues/17

I close the ticket as repeated.

**Comment by olliephillips** [comment]
I like your idea at 3) test for https connection and rewrite only those. Didn't see the other issue, but great that it was already on your radar. Best of luck with your new business too :)
