### ISSUE TITLE
Package github.com/miekg/dns/idn removal

### ISSUE THREAD

**Issue by andrewtj** [rekby/lets-proxy#45]
According to [godoc.org](https://godoc.org/github.com/miekg/dns/idn?importers) this project imports `github.com/miekg/dns/idn` which is being considered for removal as [`golang.org/x/net/idna`](http://golang.org/x/net/idna) largely supplants it. If this doesn't concern you feel free to just close this issue and move on, but otherwise please take a look at miekg/dns#518 and comment there. Thanks.

**Comment by rekby** [comment]
Thanks to question.
I have vendored your package and remove it from your repository will no broke my program.
Some later I will replace your idna by golang x.
