### ISSUE TITLE
Question on reusing when installed in image

### ISSUE THREAD

**Issue by olliephillips** [rekby/lets-proxy#48]
Should we expect any issues with lets proxy/lets encrypt when cloning an image which includes installed lets-proxy to another server on different IP.  

I ask since I'm unsure of the content of `state.json` which appears to include private keys. Are these specific to an installed instance of lets-proxy?

**Comment by rekby** [comment]
Hello.
state.json contain private of lets encrypt account. With this key you can revoke certificates.

You can use same state.json on many computer simultaneously it itsn't problem while you summary below rate limit (on account level I remember pending authorization limit only).

Or you can remote state.json - it will silent re-create while next lets-proxy start.

Attention: few days ago lets encrypt disable tls-sni authorization type for new domains, that used in lets-proxy.

https://community.letsencrypt.org/t/tls-sni-challenges-disabled-for-most-new-issuance/50316

You have to update lets-proxy to last version and proxy special directory from http to lets-proxy special port.
