### ISSUE TITLE
http reverse-proxy

### ISSUE THREAD

**Issue by rekby** [rekby/lets-proxy#49]
It need mode for bind to port 80 and proxy requests to 127.0.0.1:80 by default

**Comment by olliephillips** [comment]
Firstly, thanks for your efforts & attention to the TLS-SNI challenge problem in general. 

Re this issue - is this in preference to the server specific proxy to `localhost:4443`in the latest release or an additional feature to avoid the need for that where problematic to implement. 

It should pass-through all traffic to host, in my case Apache, except that matching the HTTP-01 validation route?

**Comment by olliephillips** [comment]
I have release v15 running and HTTP-01 challenge completing, so hopefully this issue reflects additional functionality, not replacement in respect of the http-01 proxy. Please direct me to a donate button @rekby :)

**Comment by rekby** [comment]
I think that new version will:
1. Default lets-proxy bind to all IP's but localhost (127.0.0.0/8 - ipv4 and [::1]/128 - ipv6) port 80
2. Proxy all traffic to 127.0.0.1:80 for ipv4 and [::1]:80 for ipv6 traffic. In default mode you would need to configure apache to listen port 80 with loopback (127.0.0.1) ip.
3. It will proxy all traffic but .well-known/acme-challenge/ prefix (http-01 verification)
4. lets-proxy has --target and --target-map flag. You can use it for send traffic to other ips/ports if is need.

Now lets-proxy support http-01 and tls-sni-01 modes. Existed certificates will renew until lets encrypt comlete cancel this method.
For me: i will do next version for force prefer tls-sni validation it is allowed by api (for independent of order of methods in api response from LE).

**Comment by rekby** [comment]
I have no donate button now :)

**Comment by olliephillips** [comment]
My test domain used a subdomain, which I think LE are already refusing under TNS-SNI, only fully qualified domains are good for renewal, so I presume (hope), the cert was issued on the HTTP-01 challenge. Is the type of challenge used something we can pick up in the logging so I can confirm. I've no logging to inspect currently.

Your plan above seems to have a much bigger configuration footprint than allowing the native server to proxy the single /.well-known/acme-challenge request route to new lets-proxy 127.0.0.1:4443 server as in v0.15 - maybe I'm mistaken - but what is pushing development down this route? And will the v0.15 functionality implemented now, still be an option?

**Comment by rekby** [comment]
If i right understand you ask about:
1. Feature functions ask more config then current version.
2. Save current functions/options

I want for lets-proxy start with minimal config someself (ideally - without config) and other software.
I think about what simpler - start webserver for localhost only or proxy verify requests to backend.

I want default behavior to proxy all to localhost becouse think about listen to 127.0.0.1 is much simpler, then config partially proxy, especially for non apache servers.
For partial proxy:
1. It need setup two additional modules for IIS
2. It need add location to every server part to nginx
3. I don't know about settings of Tomcat and other application servers (Tomcat, jetty, self-written software, etc).

Current method of work will available by flag: it is better then full proxy, when server handle a lot of http traffic (lets-proxy not best reverse proxy now).

**Comment by olliephillips** [comment]
You understood perfectly, thanks for the explanation. I get it.

I've only done a bit with NGINX but now you point it out, the lack of cascading directives for `server` blocks on same ip:port seems like a big omission.

Re Apache, it is very straightforward by comparison to NGINX and IIS, but user may need to load the modules `proxy` and `proxy_http`, which might be worth mentioning in the Wiki.

`a2enmod proxy proxy_http`

And great to hear the server native proxy of the http-01 challenge requests, is here to stay.
Thanks again.

**Comment by rekby** [comment]
for proxy - from apache to lets-proxy - yes. It need module.

After this issue completed - it no need additional modules.

I don't know about time for doing it (i don't know who need it). In my cases proxy verification requests is better then full proxy.

**Comment by olliephillips** [comment]
Don't build it on my account either - the traffic flow/work flow in v0.15 is perfect for my needs 
Once we have TLS we redirect http to https, so as a full proxy we'd be doubling up through lets-proxy for a lot of requests, certainly in short term. It is overkill for my needs, but I can totally see the justification for it :)

Hopefully other users can jump in and offer their feedback. Maybe add a label to the issue "feedback needed",  or "for discussion" to gain some broader input?

Build that button too :)
