### ISSUE TITLE
Renew on HTTP request?

### ISSUE THREAD

**Issue by olliephillips** [rekby/lets-proxy#51]
Currently certificate renewal is done in background I think? This creates problem where large number of subdomains are used since the renewal limit is 20 subdomains per domain per week.

Over time as more subdomains are created I have found I cannot get certificates for new subdomains and often cannot renew certs on existing subdomains because 20 is quickly used up.

With background renewal, though the subdomains may be infrequently used to access the site (each site also runs on its own www or root domain), they use up the limit of 20. 

Is it possible to have renewal of certificates run only on HTTP request, much like how certificates are issued initially now? I'm pretty sure this would smooth certificate renewal peaks so that they do not use up the 20 per week limit.

**Comment by rekby** [comment]
Now certificates renew in background, but only when it has http request.
If your domain has certificate, but doesn't requested in half year - it will get new certificate only when it has new request, not by time. But if domain has a request per day - it will renew in 30 days before end of life in background (without additional latency for client).

I don't know about lime limit - when domains count as new after certificate expire - in limit descriptions not information about this. https://letsencrypt.org/docs/rate-limits/

It has 2 way to decition of problem:
1. cron request once per day to every domain
2. add background renew function to lets-proxy - for always renew certificates.

And it need to research about renew smart schedule with limits for register new certificates:
To get the maximum possible number of certificates, you must perform all new issuances before renewals during a given time window.

**Comment by olliephillips** [comment]
Thanks for clarification on how it works. My inference was it was just based on time not triggered by request - so is it a CRON request that is forcing renewal? Maybe there can be option to disable this?

To explain my usecase better:

For me the subdomain is a little used  form of access - for when the site should not be available on it's main domain (to the public), but it still needs to be edited via a CMS. I would be quite happy if these certificates where only ever renewed when visited by a human via a browser. This is the point that https would be needed again and  the latency on that first request would be acceptable.  

When sites are built we need to also create a vhost alias on the subdomain but as stated I'm finding renewals are using up the 20 limit so that I cannot get new certificate on new subdomain at point I need it which puts a spanner in the workflow and is forcing me to remove 301 redirects from .htaccess files on a site by site basis do that at least the subdomain url is accessible via HTTP/80.

If it is CRON triggered then, having the option to disable this would probably help in my circumstances.

**Comment by rekby** [comment]
I can't distinguish browser from cron or other request source. The information doesn't contain in ssl hello request. I have only domain name at this step.
Now certificate renew when it have any request for domain. But doesn't renew when it haven't request.

If I right understand you use:
https://domain.com - for main website.
https://admin.domain.com - for edit website.

It have two domains (4 with www subdomains, but it obtained in 2 certificates) I doen't see why you need 20 or more certificates per week.

**Comment by olliephillips** [comment]
I misunderstood. If request based, and not CRON, it must be organic traffic. I am surprised, but will check the logs

Re why we exceed 20 - we do it like this:

https://customerdomain
https://customerid.admindomain (single domain for server with DNS under our control)

Thanks for confirming it is already request based.

**Comment by olliephillips** [comment]
I've discovered that renewals are actually still happening, despite us being over the 20 limit, and reading into Lets Encrypt this is intended, so I think it's the lack of traffic on the subdomain which allows the cert to expire, and then on subsequent request counts as a new certifcate that is causing the issues. I think, as you said, we'll just have to ping these domains to ensure background refresh happens, and cert not allowed to expire.
