### ISSUE TITLE
Feature to disable subdomain union

### ISSUE THREAD

**Issue by bsavelev** [rekby/lets-proxy#60]
If I need cert without subdomain, I can't do this. Is it any way to flush subdomain-union to empty list?

**Comment by rekby** [comment]
Hello, yes. You can use param --subdomains-union= or subdomains-union="" - empty line.

I did hotfix now for better work with empty list of subdomains internally (previous version can work too).
Try version v0.15.1.6 please.

**Comment by bsavelev** [comment]
it works! thx
